# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:33:55+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import (
    APIKeyHeader,
    APIKeyQuery,
    BaseSecurity,
    UnsuportedSecurityStub,
)
from fastapi import Query

from models import CollectionResponseExternalUnifiedEvent, Error, Sort

app = MCPProxy(
    description='API for accessing CRM object events.',
    title='HubSpot Events API',
    version='v3',
    servers=[{'url': 'https://api.hubapi.com/'}],
)


@app.get(
    '/events/v3/events',
    tags=['event_query_operations'],
    security=[
        APIKeyQuery(name="hapikey"),
        UnsuportedSecurityStub(name="None"),
        APIKeyHeader(name="private-app-legacy"),
    ],
)
def get__events_v3_events_get_page(
    occurred_after: Optional[datetime] = Query(None, alias='occurredAfter'),
    occurred_before: Optional[datetime] = Query(None, alias='occurredBefore'),
    object_type: Optional[str] = Query(None, alias='objectType'),
    object_id: Optional[int] = Query(None, alias='objectId'),
    event_type: Optional[str] = Query(None, alias='eventType'),
    after: Optional[str] = None,
    before: Optional[str] = None,
    limit: Optional[int] = None,
    sort: Optional[Sort] = None,
):
    """
    Returns a collection of events matching a query.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
